
/* CREATE AND INSERT DATA INTO TABLE: ROLE_PERMS */

CREATE TABLE "ROLE_PERMS" (
	ROLE_NAME VARCHAR(255) NOT NULL,
	PERMS_NAME VARCHAR(255) NOT NULL
);

INSERT INTO "ROLE_PERMS"
VALUES
('USER', 'CREATE'),
('ADMIN', 'CREATE'),
('ADMIN', 'UPDATE'),
('ADMIN', 'DELETE'),
('ADMIN', 'LIST')
;

