
/* CREATE AND INSERT DATA INTO TABLE: USER */

CREATE TABLE "USER" (
	LOGIN VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (LOGIN)
);

INSERT INTO "USER"
VALUES
('user1', 'password1', 'ADMIN'),
('user2', 'password2', 'USER')
;

